nelmio_cors:
    defaults:
        allow_credentials: false  # Be cautious with credentials when allowing all origins
        allow_origin: ['*']  # Allow all origins
        allow_headers: ['*']  # Allow all headers
        allow_methods: ['GET', 'POST', 'PATCH', 'PUT', 'DELETE', 'OPTIONS']  # Allow HTTP methods
        expose_headers: []  # Headers visible to the frontend (if needed)
        max_age: 3600  # Cache duration for preflight responses

    # Optionally, you can restrict CORS to specific routes or paths
    paths:
        '^/':
            allow_origin: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['*']
