<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_task_createtask' => [[], ['_controller' => 'App\\Controller\\TaskController::createTask'], [], [['text', '/tasks']], [], [], []],
    'app_task_gettasks' => [[], ['_controller' => 'App\\Controller\\TaskController::getTasks'], [], [['text', '/tasks']], [], [], []],
    'app_task_updatetask' => [['id'], ['_controller' => 'App\\Controller\\TaskController::updateTask'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/tasks']], [], [], []],
    'app_task_deletetask' => [['id'], ['_controller' => 'App\\Controller\\TaskController::deleteTask'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/tasks']], [], [], []],
    'App\Controller\TaskController::createTask' => [[], ['_controller' => 'App\\Controller\\TaskController::createTask'], [], [['text', '/tasks']], [], [], []],
    'App\Controller\TaskController::getTasks' => [[], ['_controller' => 'App\\Controller\\TaskController::getTasks'], [], [['text', '/tasks']], [], [], []],
    'App\Controller\TaskController::updateTask' => [['id'], ['_controller' => 'App\\Controller\\TaskController::updateTask'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/tasks']], [], [], []],
    'App\Controller\TaskController::deleteTask' => [['id'], ['_controller' => 'App\\Controller\\TaskController::deleteTask'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/tasks']], [], [], []],
];
